version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bedrock_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bedrock
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bedrock_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wpuser
      PMA_PASSWORD: wppass

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bedrock_php
    volumes:
      - .:/var/www/html
    user: "1000:1000"
    ports:
      - "9000:9000"
    environment:
      - UID=1000
      - GID=1000
      - WORDPRESS_ENV=development
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: bedrock_nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

volumes:
  db_data: